spring:
  datasource:
    username: root
    password: 118439367qQ
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.195.139:3306/coronavirus?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    open-in-view: true
#  thymeleaf:
#    cache: false
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

server:
  port: 8080